#' @title plot_growth_curve
#' @description Visualization of growth curve from Optical Density values generated by spectrophotometer like Cytation3
#'
#' @param dat_growth_curve a tibble, with first column as `Time` and after that
#'   columns as samples. If the samples have replicates mention them as
#'   `sampleName_replicate`, for example `CgFlu_R1` , `CgFlu_R2`, `CgFlu_R3`
#' @param average_replicates logical, to plot average and standard deviation of
#'   replicates, Default: FALSE
#' @param select_replicates a vector, define replicates to be selected to plot,
#'   it should be anything after `_`. for eg. if only replicate R1 and R2 need
#'   to be plotted from samples CgFlu_R1, CgFlu_R2; the vector should be
#'   `c("R1", "R2")`, Default: NULL
#' @param end_timepoint numeric, the end time-point to be considered. Default:NULL (end-timepoint from data)
#' @param palette_name character,name palettes Default: 'all_colors'
#' For individual palette;
#'  \itemize{
#'  \item {Accent: }{8}
#'  \item {Dark2: }{8}
#'  \item {Paired: }{12}
#'  \item {Pastel1: }{9}
#'  \item {Pastel2: }{8}
#'  \item {Set1: }{9}
#'  \item {Set2: }{8}
#'  \item {Set3: }{12} }
#' @param custom_colors character vector of defined colors
#' @return a plot of growth curve
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'
#'   plot_growth_curve(dat_growth_curve = yeast_growth_data,average_replicates=TRUE, select_replicates=c("R1", "R2"), custom_colors=NULL)
#'
#'   }
#' }
#' @seealso
#'  \code{\link[tidyr]{gather}},\code{\link[tidyr]{separate}}
#'  \code{\link[dplyr]{filter}},\code{\link[dplyr]{mutate}},\code{\link[dplyr]{group_by}},\code{\link[dplyr]{select}}
#'  \code{\link[forcats]{as_factor}}
#'  \code{\link[ggplot2]{ggplot}},\code{\link[ggplot2]{aes}},\code{\link[ggplot2]{geom_point}},\code{\link[ggplot2]{geom_path}},\code{\link[ggplot2]{geom_crossbar}},\code{\link[ggplot2]{position_dodge}},\code{\link[ggplot2]{labs}},\code{\link[ggplot2]{facet_grid}},\code{\link[ggplot2]{theme}},\code{\link[ggplot2]{margin}},\code{\link[ggplot2]{ggtheme}},\code{\link[ggplot2]{scale_manual}}
#'  \code{\link[RColorBrewer]{RColorBrewer}}
#' @rdname plot_growth_curve
#' @export
#' @importFrom tidyr gather separate
#' @importFrom dplyr filter mutate group_by select
#' @importFrom forcats as_factor
#' @importFrom ggplot2 ggplot aes geom_point geom_line geom_errorbar position_dodge ylab facet_grid theme element_blank element_text theme_bw xlab scale_color_manual
#' @importFrom RColorBrewer brewer.pal
#' @import magrittr
plot_growth_curve <- function(dat_growth_curve, average_replicates=FALSE, select_replicates=NULL, palette_name="all_colors",custom_colors=NULL, end_timepoint=NULL){

            column1 <- dat_growth_curve %>% colnames() %>% .[1]

            dat_growth_curve <- dat_growth_curve %>%
                            dplyr::rename(Time= column1)

          if(is.null(end_timepoint)==FALSE){
            dat_growth_curve <- dat_growth_curve %>%
              dplyr::filter(Time <= end_timepoint)
          }
          else{
            dat_growth_curve <- dat_growth_curve
          }

         dat_melt <- dat_growth_curve %>%
                          tidyr::gather(key="sample", value="OD", -Time) %>%
                          tidyr::separate(col = sample,into = c("condition","replicate"),sep="_")

         if(is.null(select_replicates)==FALSE){
           dat_melt <- dat_melt %>%
                          dplyr::filter(replicate %in% select_replicates)
         }
         else{
           dat_melt <- dat_melt
         }



  if (average_replicates==TRUE){

    summ_dat <- dat_melt %>%
                    dplyr::mutate(condition=forcats::as_factor(condition)) %>%
                    dplyr::group_by(.dots = c("Time", "condition"))  %>%
                    dplyr::mutate(sd = sd(OD), mean=mean(OD)) %>%
                    dplyr::filter(replicate==min(replicate)) %>%
                    dplyr::select(-c(replicate))


    gg_growth <- ggplot2::ggplot(summ_dat,ggplot2::aes(Time, mean, color=condition)) +
                    ggplot2::geom_point()+
                    ggplot2::geom_line(lwd=0.8)+
                    ggplot2::geom_errorbar(ggplot2::aes(ymin=mean-sd, ymax=mean+sd),
                                  width=.2,position=ggplot2::position_dodge(0.05))+ggplot2::ylab("mean(OD600)")
  }

        else{

          summ_dat <- dat_melt %>%
                      dplyr::mutate(condition=forcats::as_factor(condition))

          gg_growth <- ggplot2::ggplot(summ_dat,ggplot2::aes(Time, OD, color=condition))+
                          ggplot2::geom_point()+
                          ggplot2::geom_line(lwd=0.8)+
                          ggplot2::facet_grid(~replicate)+
                          ggplot2::ylab("OD600")

        }

         gg_growth <- gg_growth +
                      ggplot2::theme(panel.grid = ggplot2::element_blank(),
                                     axis.text = ggplot2::element_text(color="black", size=12))+
                      ggplot2::theme_bw()+
                      ggplot2::xlab("Time (in hours)")+
                      ggplot2::theme(axis.text = ggplot2::element_text(size = 14, colour = "black"),
                                     legend.text = ggplot2::element_text(size = 12, colour = "black", face = "bold"),
                                     legend.title = ggplot2::element_blank(),
                        panel.grid.minor = ggplot2::element_blank())+
                      #ggplot2::scale_color_manual(values = growkar:::select_palette(num_of_colors = length(unique(summ_dat$condition)), palette_name = palette_name))
                      ggplot2::scale_color_manual(
                                     values = if (!is.null(custom_colors)) {
                                       custom_colors
                                     } else {
                                       growkar:::select_palette(num_of_colors = length(unique(summ_dat$condition)),
                                                                palette_name = palette_name)
                                     }
                                   )


         return(gg_growth)



}
