
dat_growth_curve <- readr::read_delim(pipe("pbpaste"), delim="\t",col_names = TRUE)
#' @title plot_growth_curve
#' @description Visualization of growth curve from Optical Density values generated by spectrophotometer like Cytation3
#' @param dat_growth_curve a tibble, with first column as `Time` and after that
#'   columns as samples. If the samples have replicates mention them as
#'   `sampleName_replicate`, for example `ScPH4_R1` , `ScPH4_R2`, `ScPH4_R3`
#' @param average_replicates logical, to plot average and standard deviation of
#'   replicates, Default: FALSE
#' @param select_replicate  a vector, define replicates to be selected to plot,
#'   it should be anything after `_`. for eg. if only replicate R1 and R2 need
#'   to be plotted from samples ScPH4_R1, ScPH4_R2; the vector should be
#'   `c("R1", "R2")`, Default: NULL
#' @return a plot of growth curve
#' @details DETAILS
#' @examples
#' \dontrun{
#' if(interactive()){
#'   plot_growth_curve(dat_growth_curve = yeast_growth_data,average_replicates=TRUE, select_replicates=c("R1", "R2"))
#'  }
#' }
#' @seealso
#'  \code{\link[tidyr]{gather}},\code{\link[tidyr]{separate}}
#'  \code{\link[dplyr]{filter}},\code{\link[dplyr]{mutate}},\code{\link[dplyr]{group_by}},\code{\link[dplyr]{select}}
#'  \code{\link[forcats]{as_factor}}
#'  \code{\link[ggplot2]{ggplot}},\code{\link[ggplot2]{aes}},\code{\link[ggplot2]{geom_point}},\code{\link[ggplot2]{geom_path}},\code{\link[ggplot2]{geom_crossbar}},\code{\link[ggplot2]{position_dodge}},\code{\link[ggplot2]{labs}},\code{\link[ggplot2]{facet_grid}},\code{\link[ggplot2]{theme}},\code{\link[ggplot2]{margin}},\code{\link[ggplot2]{ggtheme}},\code{\link[ggplot2]{scale_manual}}
#'  \code{\link[RColorBrewer]{RColorBrewer}}
#' @rdname plot_growth_curve
#' @export
#' @importFrom tidyr gather separate
#' @importFrom dplyr filter mutate group_by select
#' @importFrom forcats as_factor
#' @importFrom ggplot2 ggplot aes geom_point geom_line geom_errorbar position_dodge ylab facet_grid theme element_blank element_text theme_bw xlab scale_color_manual
#' @importFrom RColorBrewer brewer.pal
#' @import magrittr
plot_growth_curve <- function(dat_growth_curve, average_replicates=FALSE, select_replicates=NULL){

        library(magrittr)

         dat_melt <- dat_growth_curve %>%
                          tidyr::gather(key="sample", value="OD", -Time) %>%
                          tidyr::separate(col = sample,into = c("condition","replicate"),sep="_")

         if(is.null(select_replicates)==FALSE){
           dat_melt <- dat_melt %>%
                          dplyr::filter(replicate %in% select_replicates)
         }
         else{
           dat_melt <- dat_melt
         }

  if (average_replicates==TRUE){

    summ_dat <- dat_melt %>%
                    dplyr::mutate(condition=forcats::as_factor(condition)) %>%
                    dplyr::group_by(.dots = c("Time", "condition"))  %>%
                    dplyr::mutate(sd = sd(OD), mean=mean(OD)) %>%
                    dplyr::filter(replicate==min(replicate)) %>%
                    dplyr::select(-c(replicate))


    gg_growth <- ggplot2::ggplot(summ_dat,ggplot2::aes(Time, mean, color=condition)) +
                    ggplot2::geom_point()+
                    ggplot2::geom_line(lwd=0.8)+
                    ggplot2::geom_errorbar(ggplot2::aes(ymin=mean-sd, ymax=mean+sd),
                                  width=.2,position=ggplot2::position_dodge(0.05))+ggplot2::ylab("mean(OD600)")
  }

        else{

          summ_dat <- dat_melt %>%
                      dplyr::mutate(condition=forcats::as_factor(condition))

          gg_growth <- ggplot2::ggplot(summ_dat,ggplot2::aes(Time, OD, color=condition))+
                          ggplot2::geom_point()+
                          ggplot2::geom_line(lwd=0.8)+
                          ggplot2::facet_grid(~replicate)+
                          ggplot2::ylab("OD600")

        }

         gg_growth <- gg_growth +
                      ggplot2::theme(panel.grid = ggplot2::element_blank(),
                                     axis.text = ggplot2::element_text(color="black", size=12))+
                      ggplot2::theme_bw()+
                      ggplot2::xlab("Time (in hours)")+
                      ggplot2::theme(axis.text = ggplot2::element_text(size = 14, colour = "black"),
                                     legend.text = ggplot2::element_text(size = 12, colour = "black", face = "bold"),
                                     legend.title = ggplot2::element_blank(),
                        panel.grid.minor = ggplot2::element_blank())+
                      ggplot2::scale_color_manual(values = RColorBrewer::brewer.pal(length(unique(summ_dat$condition)), "Set1"))



         return(gg_growth)



}
