name: R-CMD-check

on:
  push:
    branches:
      - main
      - master
      - tidy-v2
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      # Check the package with the standard r-lib action stack.
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Bioconductor core dependencies
        run: |
          install.packages("BiocManager", repos = "https://cloud.r-project.org")
          BiocManager::install(
            c("SummarizedExperiment", "S4Vectors"),
            ask = FALSE,
            update = FALSE
          )
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual")'
